
import cz.muni.fi.pa165.bookingmanager.ws.generated.Customer;
import cz.muni.fi.pa165.bookingmanager.ws.generated.Hotel;
import java.math.BigInteger;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import webServiceClient.WebServiceClient;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Robert
 */
public class MainFrame extends javax.swing.JFrame {

    WebServiceClient webServiceClient;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setTitle("Booking manager");
        
        ApplicationContext context = new ClassPathXmlApplicationContext ( "clientApplicationContext.xml" );
        webServiceClient = ( WebServiceClient ) context.getBean ( "webServiceClient" );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        loadHotelsButton = new javax.swing.JButton();
        addHotelButton = new javax.swing.JButton();
        editHotelButton = new javax.swing.JButton();
        deleteHotelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hotelList = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        loadCustomersButton = new javax.swing.JButton();
        addCustomerButton = new javax.swing.JButton();
        editCustomerButton = new javax.swing.JButton();
        deleteCustomerButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadHotelsButton.setText("Load Hotels");
        loadHotelsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadHotelsButtonActionPerformed(evt);
            }
        });

        addHotelButton.setText("Add Hotel");
        addHotelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHotelButtonActionPerformed(evt);
            }
        });

        editHotelButton.setText("Edit Hotel");
        editHotelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editHotelButtonActionPerformed(evt);
            }
        });

        deleteHotelButton.setText("Delete Hotel");
        deleteHotelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteHotelButtonActionPerformed(evt);
            }
        });

        hotelList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Address", "Phone number"
            }
        ));
        jScrollPane1.setViewportView(hotelList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteHotelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(editHotelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addHotelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadHotelsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loadHotelsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addHotelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editHotelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteHotelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane4.addTab("Hotels", jPanel1);

        loadCustomersButton.setText("Load Customers");
        loadCustomersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCustomersButtonActionPerformed(evt);
            }
        });

        addCustomerButton.setText("Add Customer");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        editCustomerButton.setText("Edit Customer");
        editCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerButtonActionPerformed(evt);
            }
        });

        deleteCustomerButton.setText("Delete Customer");
        deleteCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerButtonActionPerformed(evt);
            }
        });

        customerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Name", "Address"
            }
        ));
        jScrollPane2.setViewportView(customerList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(editCustomerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCustomerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadCustomersButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(loadCustomersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane4.addTab("Customers", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        jTabbedPane4.getAccessibleContext().setAccessibleName("Hotels");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        AddCustomerFrame addCustomerFrame = new AddCustomerFrame(this, webServiceClient);
        addCustomerFrame.setVisible(true);
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void editCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerButtonActionPerformed
        if (customerList.getSelectedRowCount() != 1){
            TableSelectErrorDialog tableSelectErrorDialog = new TableSelectErrorDialog(this, false);
            tableSelectErrorDialog.setVisible(true);
        } else {
            int index = customerList.getSelectedRow();
            
            BigInteger id = (BigInteger) customerList.getValueAt(index, 0);
            String name = (String) customerList.getValueAt(index, 1);
            String address = (String) customerList.getValueAt(index, 2);
            
            EditCustomerFrame editCustomerFrame = new EditCustomerFrame(this, id, name, address, webServiceClient);
            editCustomerFrame.setVisible(true);
        }
        
    }//GEN-LAST:event_editCustomerButtonActionPerformed

    private void deleteCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerButtonActionPerformed
        if (customerList.getSelectedRowCount() != 1){
            TableSelectErrorDialog tableSelectErrorDialog = new TableSelectErrorDialog(this, false);
            tableSelectErrorDialog.setVisible(true);
        } else {
            int index = customerList.getSelectedRow();
            BigInteger id = (BigInteger) customerList.getValueAt(index, 0);
            
            webServiceClient.sendCustomerRemoveRequest(id);
        }
    }//GEN-LAST:event_deleteCustomerButtonActionPerformed

    private void addHotelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHotelButtonActionPerformed
        AddHotelFrame addHotelFrame = new AddHotelFrame(this, webServiceClient);
        addHotelFrame.setVisible(true);
    }//GEN-LAST:event_addHotelButtonActionPerformed

    private void editHotelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editHotelButtonActionPerformed
        if (hotelList.getSelectedRowCount() != 1){
            TableSelectErrorDialog tableSelectErrorDialog = new TableSelectErrorDialog(this, false);
            tableSelectErrorDialog.setVisible(true);
        } else {
            int index = hotelList.getSelectedRow();
            
            BigInteger id = (BigInteger) hotelList.getValueAt(index, 0);
            String name = (String) hotelList.getValueAt(index, 1);
            String address = (String) hotelList.getValueAt(index, 2);
            String phoneNumber = (String) hotelList.getValueAt(index, 3);
            
            EditHotelFrame editHotelFrame = new EditHotelFrame(this, id.toString(), name, address, phoneNumber, webServiceClient);
            editHotelFrame.setVisible(true);
        }
        
    }//GEN-LAST:event_editHotelButtonActionPerformed

    private void loadHotelsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadHotelsButtonActionPerformed
        List<Hotel> hotels = webServiceClient.sendGetAllHotelsRequest();
        
        Object[] columnNames = {"Id", "Name", "Address", "Phone number"};
        DefaultTableModel model = new DefaultTableModel(new Object[0][0], columnNames);
        
        for (Hotel hotel: hotels){
            
            Object[] rowData = new Object[4];
            
            rowData[0] = hotel.getId();
            rowData[1] = hotel.getName();
            rowData[2] = hotel.getAddress();
            rowData[3] = hotel.getPhoneNumber();
            
            model.addRow(rowData);
        }
        hotelList.setModel(model);
        model.fireTableDataChanged();
    }//GEN-LAST:event_loadHotelsButtonActionPerformed

    private void deleteHotelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteHotelButtonActionPerformed
        if (hotelList.getSelectedRowCount() != 1){
            TableSelectErrorDialog tableSelectErrorDialog = new TableSelectErrorDialog(this, false);
            tableSelectErrorDialog.setVisible(true);
        } else {
            int index = hotelList.getSelectedRow();
            BigInteger id = (BigInteger) hotelList.getValueAt(index, 0);
            
            webServiceClient.sendHotelRemoveRequest(id);
        }
    }//GEN-LAST:event_deleteHotelButtonActionPerformed

    private void loadCustomersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCustomersButtonActionPerformed
        List<Customer> customers = webServiceClient.sendGetAllCustomersRequest();
        
        Object[] columnNames = {"Id", "Name", "Address"};
        DefaultTableModel model = new DefaultTableModel(new Object[0][0], columnNames);
        
        for (Customer customer: customers){
            
            Object[] rowData = new Object[3];
            
            rowData[0] = customer.getId();
            rowData[1] = customer.getName();
            rowData[2] = customer.getAddress();
            
            model.addRow(rowData);
        }
        customerList.setModel(model);
        model.fireTableDataChanged();
    }//GEN-LAST:event_loadCustomersButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JButton addHotelButton;
    private javax.swing.JTable customerList;
    private javax.swing.JButton deleteCustomerButton;
    private javax.swing.JButton deleteHotelButton;
    private javax.swing.JButton editCustomerButton;
    private javax.swing.JButton editHotelButton;
    private javax.swing.JTable hotelList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton loadCustomersButton;
    private javax.swing.JButton loadHotelsButton;
    // End of variables declaration//GEN-END:variables
}
